[tool.black]
line-length = 120
exclude = '''
/(
    \.venv
  | node_modules
  | __pycache__
  | migrations
)/'''

[tool.isort]
profile = "black"
line_length = 120
skip = [".venv", "node_modules", "__pycache__", "migrations"]
